// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: auth_session.proto

package epic_urc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to User:
	//
	//	*TargetUser_UserToken
	User          isTargetUser_User `protobuf_oneof:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetUser) Reset() {
	*x = TargetUser{}
	mi := &file_auth_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetUser) ProtoMessage() {}

func (x *TargetUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetUser.ProtoReflect.Descriptor instead.
func (*TargetUser) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{0}
}

func (x *TargetUser) GetUser() isTargetUser_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TargetUser) GetUserToken() string {
	if x != nil {
		if x, ok := x.User.(*TargetUser_UserToken); ok {
			return x.UserToken
		}
	}
	return ""
}

type isTargetUser_User interface {
	isTargetUser_User()
}

type TargetUser_UserToken struct {
	UserToken string `protobuf:"bytes,1,opt,name=user_token,proto3,oneof"`
}

func (*TargetUser_UserToken) isTargetUser_User() {}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_auth_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{1}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_auth_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientState   string                 `protobuf:"bytes,1,opt,name=client_state,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAuthSessionRequest) Reset() {
	*x = StartAuthSessionRequest{}
	mi := &file_auth_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthSessionRequest) ProtoMessage() {}

func (x *StartAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*StartAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{3}
}

func (x *StartAuthSessionRequest) GetClientState() string {
	if x != nil {
		return x.ClientState
	}
	return ""
}

type StartAuthSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCode   string                 `protobuf:"bytes,1,opt,name=session_code,proto3"`
	LoginUrl      string                 `protobuf:"bytes,2,opt,name=login_url,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAuthSessionResponse) Reset() {
	*x = StartAuthSessionResponse{}
	mi := &file_auth_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthSessionResponse) ProtoMessage() {}

func (x *StartAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*StartAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{4}
}

func (x *StartAuthSessionResponse) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

func (x *StartAuthSessionResponse) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

type GetAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCode   string                 `protobuf:"bytes,1,opt,name=session_code,proto3"`
	ClientState   string                 `protobuf:"bytes,2,opt,name=client_state,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthSessionRequest) Reset() {
	*x = GetAuthSessionRequest{}
	mi := &file_auth_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthSessionRequest) ProtoMessage() {}

func (x *GetAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*GetAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthSessionRequest) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

func (x *GetAuthSessionRequest) GetClientState() string {
	if x != nil {
		return x.ClientState
	}
	return ""
}

type GetAuthSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,proto3,oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthSessionResponse) Reset() {
	*x = GetAuthSessionResponse{}
	mi := &file_auth_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthSessionResponse) ProtoMessage() {}

func (x *GetAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*GetAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthSessionResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

type RefreshAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthSessionRequest) Reset() {
	*x = RefreshAuthSessionRequest{}
	mi := &file_auth_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthSessionRequest) ProtoMessage() {}

func (x *RefreshAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{7}
}

type RefreshAuthSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,proto3,oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthSessionResponse) Reset() {
	*x = RefreshAuthSessionResponse{}
	mi := &file_auth_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthSessionResponse) ProtoMessage() {}

func (x *RefreshAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_session_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshAuthSessionResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

var File_auth_session_proto protoreflect.FileDescriptor

const file_auth_session_proto_rawDesc = "" +
	"\n" +
	"\x12auth_session.proto\x12\bepic_urc\x1a\x10auth_token.proto\"5\n" +
	"\n" +
	"TargetUser\x12\x1f\n" +
	"\n" +
	"user_token\x18\x01 \x01(\tH\x00R\tuserTokenB\x06\n" +
	"\x04user\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"<\n" +
	"\x17StartAuthSessionRequest\x12!\n" +
	"\fclient_state\x18\x01 \x01(\tR\vclientState\"Z\n" +
	"\x18StartAuthSessionResponse\x12!\n" +
	"\fsession_code\x18\x01 \x01(\tR\vsessionCode\x12\x1b\n" +
	"\tlogin_url\x18\x02 \x01(\tR\bloginUrl\"]\n" +
	"\x15GetAuthSessionRequest\x12!\n" +
	"\fsession_code\x18\x01 \x01(\tR\vsessionCode\x12!\n" +
	"\fclient_state\x18\x02 \x01(\tR\vclientState\"`\n" +
	"\x16GetAuthSessionResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_token\"\x1b\n" +
	"\x19RefreshAuthSessionRequest\"d\n" +
	"\x1aRefreshAuthSessionResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_tokenBDZBgithub.com/lorehub/lorehub/services/api/internal/loreauth/epic_urcb\x06proto3"

var (
	file_auth_session_proto_rawDescOnce sync.Once
	file_auth_session_proto_rawDescData []byte
)

func file_auth_session_proto_rawDescGZIP() []byte {
	file_auth_session_proto_rawDescOnce.Do(func() {
		file_auth_session_proto_rawDescData = protoimpl.X.CompressGZIP(
			unsafe.Slice(unsafe.StringData(file_auth_session_proto_rawDesc), len(file_auth_session_proto_rawDesc)),
		)
	})
	return file_auth_session_proto_rawDescData
}

var file_auth_session_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_auth_session_proto_goTypes = []any{
	(*TargetUser)(nil),                 // 0: epic_urc.TargetUser
	(*HealthCheckRequest)(nil),         // 1: epic_urc.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 2: epic_urc.HealthCheckResponse
	(*StartAuthSessionRequest)(nil),    // 3: epic_urc.StartAuthSessionRequest
	(*StartAuthSessionResponse)(nil),   // 4: epic_urc.StartAuthSessionResponse
	(*GetAuthSessionRequest)(nil),      // 5: epic_urc.GetAuthSessionRequest
	(*GetAuthSessionResponse)(nil),     // 6: epic_urc.GetAuthSessionResponse
	(*RefreshAuthSessionRequest)(nil),  // 7: epic_urc.RefreshAuthSessionRequest
	(*RefreshAuthSessionResponse)(nil), // 8: epic_urc.RefreshAuthSessionResponse
	(*UserToken)(nil),                  // 9: epic_urc.UserToken
}
var file_auth_session_proto_depIdxs = []int32{
	9, // 0: epic_urc.GetAuthSessionResponse.user_token:type_name -> epic_urc.UserToken
	9, // 1: epic_urc.RefreshAuthSessionResponse.user_token:type_name -> epic_urc.UserToken
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_session_proto_init() }
func file_auth_session_proto_init() {
	if File_auth_session_proto != nil {
		return
	}
	file_auth_token_proto_init()
	file_auth_session_proto_msgTypes[0].OneofWrappers = []any{
		(*TargetUser_UserToken)(nil),
	}
	file_auth_session_proto_msgTypes[6].OneofWrappers = []any{}
	file_auth_session_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(
				unsafe.StringData(file_auth_session_proto_rawDesc),
				len(file_auth_session_proto_rawDesc),
			),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_session_proto_goTypes,
		DependencyIndexes: file_auth_session_proto_depIdxs,
		MessageInfos:      file_auth_session_proto_msgTypes,
	}.Build()
	File_auth_session_proto = out.File
	file_auth_session_proto_goTypes = nil
	file_auth_session_proto_depIdxs = nil
}
