// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: auth_permission.proto

package epic_urc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourcePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,proto3"`
	Permission    []string               `protobuf:"bytes,2,rep,name=permission,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcePermission) Reset() {
	*x = ResourcePermission{}
	mi := &file_auth_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePermission) ProtoMessage() {}

func (x *ResourcePermission) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePermission.ProtoReflect.Descriptor instead.
func (*ResourcePermission) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{0}
}

func (x *ResourcePermission) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourcePermission) GetPermission() []string {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ExchangeUserTokenForMultiresourceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    []string               `protobuf:"bytes,1,rep,name=resource_id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) Reset() {
	*x = ExchangeUserTokenForMultiresourceTokenRequest{}
	mi := &file_auth_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeUserTokenForMultiresourceTokenRequest) ProtoMessage() {}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeUserTokenForMultiresourceTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeUserTokenForMultiresourceTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) GetResourceId() []string {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

type ExchangeUserTokenForMultiresourceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *UserToken             `protobuf:"bytes,1,opt,name=token,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) Reset() {
	*x = ExchangeUserTokenForMultiresourceTokenResponse{}
	mi := &file_auth_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeUserTokenForMultiresourceTokenResponse) ProtoMessage() {}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeUserTokenForMultiresourceTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeUserTokenForMultiresourceTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) GetToken() *UserToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type CheckUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    []string               `protobuf:"bytes,1,rep,name=resource_id,proto3"`
	TargetUser    *TargetUser            `protobuf:"bytes,2,opt,name=target_user,proto3,oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserPermissionRequest) Reset() {
	*x = CheckUserPermissionRequest{}
	mi := &file_auth_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPermissionRequest) ProtoMessage() {}

func (x *CheckUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUserPermissionRequest) GetResourceId() []string {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

func (x *CheckUserPermissionRequest) GetTargetUser() *TargetUser {
	if x != nil {
		return x.TargetUser
	}
	return nil
}

type CheckUserPermissionResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AllowedResourcePermission []*ResourcePermission  `protobuf:"bytes,1,rep,name=allowed_resource_permission,proto3"`
	DeniedResourcePermission  []*ResourcePermission  `protobuf:"bytes,2,rep,name=denied_resource_permission,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CheckUserPermissionResponse) Reset() {
	*x = CheckUserPermissionResponse{}
	mi := &file_auth_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPermissionResponse) ProtoMessage() {}

func (x *CheckUserPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckUserPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUserPermissionResponse) GetAllowedResourcePermission() []*ResourcePermission {
	if x != nil {
		return x.AllowedResourcePermission
	}
	return nil
}

func (x *CheckUserPermissionResponse) GetDeniedResourcePermission() []*ResourcePermission {
	if x != nil {
		return x.DeniedResourcePermission
	}
	return nil
}

type LookupUserPermissionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceFilter string                 `protobuf:"bytes,1,opt,name=resource_filter,proto3"`
	ContextFilter  *string                `protobuf:"bytes,2,opt,name=context_filter,proto3,oneof"`
	PageSize       *int32                 `protobuf:"varint,3,opt,name=page_size,proto3,oneof"`
	PageToken      *string                `protobuf:"bytes,4,opt,name=page_token,proto3,oneof"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookupUserPermissionsRequest) Reset() {
	*x = LookupUserPermissionsRequest{}
	mi := &file_auth_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupUserPermissionsRequest) ProtoMessage() {}

func (x *LookupUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*LookupUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{5}
}

func (x *LookupUserPermissionsRequest) GetResourceFilter() string {
	if x != nil {
		return x.ResourceFilter
	}
	return ""
}

func (x *LookupUserPermissionsRequest) GetContextFilter() string {
	if x != nil && x.ContextFilter != nil {
		return *x.ContextFilter
	}
	return ""
}

func (x *LookupUserPermissionsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *LookupUserPermissionsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type LookupUserPermissionsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourcePermission []*ResourcePermission  `protobuf:"bytes,1,rep,name=resource_permission,proto3"`
	NextPageToken      *string                `protobuf:"bytes,2,opt,name=next_page_token,proto3,oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LookupUserPermissionsResponse) Reset() {
	*x = LookupUserPermissionsResponse{}
	mi := &file_auth_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupUserPermissionsResponse) ProtoMessage() {}

func (x *LookupUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*LookupUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_permission_proto_rawDescGZIP(), []int{6}
}

func (x *LookupUserPermissionsResponse) GetResourcePermission() []*ResourcePermission {
	if x != nil {
		return x.ResourcePermission
	}
	return nil
}

func (x *LookupUserPermissionsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

var File_auth_permission_proto protoreflect.FileDescriptor

const file_auth_permission_proto_rawDesc = "" +
	"\n" +
	"\x15auth_permission.proto\x12\bepic_urc\x1a\x12auth_session.proto\x1a\x10auth_token.proto\"U\n" +
	"\x12ResourcePermission\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x03(\tR\n" +
	"permission\"P\n" +
	"-ExchangeUserTokenForMultiresourceTokenRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x03(\tR\n" +
	"resourceId\"[\n" +
	".ExchangeUserTokenForMultiresourceTokenResponse\x12)\n" +
	"\x05token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenR\x05token\"\x89\x01\n" +
	"\x1aCheckUserPermissionRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x03(\tR\n" +
	"resourceId\x12:\n" +
	"\vtarget_user\x18\x02 \x01(\v2\x14.epic_urc.TargetUserH\x00R\n" +
	"targetUser\x88\x01\x01B\x0e\n" +
	"\f_target_user\"\xd7\x01\n" +
	"\x1bCheckUserPermissionResponse\x12\\\n" +
	"\x1ballowed_resource_permission\x18\x01 \x03(\v2\x1c.epic_urc.ResourcePermissionR" +
	"\x19allowedResourcePermission\x12Z\n" +
	"\x1adenied_resource_permission\x18\x02 \x03(\v2\x1c.epic_urc.ResourcePermissionR" +
	"\x18deniedResourcePermission\"\xe9\x01\n" +
	"\x1cLookupUserPermissionsRequest\x12'\n" +
	"\x0fresource_filter\x18\x01 \x01(\tR\x0eresourceFilter\x12*\n" +
	"\x0econtext_filter\x18\x02 \x01(\tH\x00R\rcontextFilter\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x02R\tpageToken\x88\x01\x01B\x11\n" +
	"\x0f_context_filterB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xaf\x01\n" +
	"\x1dLookupUserPermissionsResponse\x12M\n" +
	"\x13resource_permission\x18\x01 \x03(\v2\x1c.epic_urc.ResourcePermissionR\x12resourcePermission\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_tokenBDZBgithub.com/lorehub/lorehub/services/api/internal/loreauth/epic_urcb\x06proto3"

var (
	file_auth_permission_proto_rawDescOnce sync.Once
	file_auth_permission_proto_rawDescData []byte
)

func file_auth_permission_proto_rawDescGZIP() []byte {
	file_auth_permission_proto_rawDescOnce.Do(func() {
		file_auth_permission_proto_rawDescData = protoimpl.X.CompressGZIP(
			unsafe.Slice(unsafe.StringData(file_auth_permission_proto_rawDesc), len(file_auth_permission_proto_rawDesc)),
		)
	})
	return file_auth_permission_proto_rawDescData
}

var file_auth_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_permission_proto_goTypes = []any{
	(*ResourcePermission)(nil),                             // 0: epic_urc.ResourcePermission
	(*ExchangeUserTokenForMultiresourceTokenRequest)(nil),  // 1: epic_urc.ExchangeUserTokenForMultiresourceTokenRequest
	(*ExchangeUserTokenForMultiresourceTokenResponse)(nil), // 2: epic_urc.ExchangeUserTokenForMultiresourceTokenResponse
	(*CheckUserPermissionRequest)(nil),                     // 3: epic_urc.CheckUserPermissionRequest
	(*CheckUserPermissionResponse)(nil),                    // 4: epic_urc.CheckUserPermissionResponse
	(*LookupUserPermissionsRequest)(nil),                   // 5: epic_urc.LookupUserPermissionsRequest
	(*LookupUserPermissionsResponse)(nil),                  // 6: epic_urc.LookupUserPermissionsResponse
	(*UserToken)(nil),                                      // 7: epic_urc.UserToken
	(*TargetUser)(nil),                                     // 8: epic_urc.TargetUser
}
var file_auth_permission_proto_depIdxs = []int32{
	7, // 0: epic_urc.ExchangeUserTokenForMultiresourceTokenResponse.token:type_name -> epic_urc.UserToken
	8, // 1: epic_urc.CheckUserPermissionRequest.target_user:type_name -> epic_urc.TargetUser
	0, // 2: epic_urc.CheckUserPermissionResponse.allowed_resource_permission:type_name -> epic_urc.ResourcePermission
	0, // 3: epic_urc.CheckUserPermissionResponse.denied_resource_permission:type_name -> epic_urc.ResourcePermission
	0, // 4: epic_urc.LookupUserPermissionsResponse.resource_permission:type_name -> epic_urc.ResourcePermission
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_auth_permission_proto_init() }
func file_auth_permission_proto_init() {
	if File_auth_permission_proto != nil {
		return
	}
	file_auth_session_proto_init()
	file_auth_token_proto_init()
	file_auth_permission_proto_msgTypes[3].OneofWrappers = []any{}
	file_auth_permission_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_permission_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(
				unsafe.StringData(file_auth_permission_proto_rawDesc),
				len(file_auth_permission_proto_rawDesc),
			),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_permission_proto_goTypes,
		DependencyIndexes: file_auth_permission_proto_depIdxs,
		MessageInfos:      file_auth_permission_proto_msgTypes,
	}.Build()
	File_auth_permission_proto = out.File
	file_auth_permission_proto_goTypes = nil
	file_auth_permission_proto_depIdxs = nil
}
