// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: auth_exchange.proto

package epic_urc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyCompliance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCompliance) Reset() {
	*x = VerifyCompliance{}
	mi := &file_auth_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCompliance) ProtoMessage() {}

func (x *VerifyCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCompliance.ProtoReflect.Descriptor instead.
func (*VerifyCompliance) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCompliance) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type VerifyRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Requirement:
	//
	//	*VerifyRequirement_Compliance
	Requirement   isVerifyRequirement_Requirement `protobuf_oneof:"requirement"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequirement) Reset() {
	*x = VerifyRequirement{}
	mi := &file_auth_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequirement) ProtoMessage() {}

func (x *VerifyRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequirement.ProtoReflect.Descriptor instead.
func (*VerifyRequirement) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyRequirement) GetRequirement() isVerifyRequirement_Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *VerifyRequirement) GetCompliance() *VerifyCompliance {
	if x != nil {
		if x, ok := x.Requirement.(*VerifyRequirement_Compliance); ok {
			return x.Compliance
		}
	}
	return nil
}

type isVerifyRequirement_Requirement interface {
	isVerifyRequirement_Requirement()
}

type VerifyRequirement_Compliance struct {
	Compliance *VerifyCompliance `protobuf:"bytes,2,opt,name=compliance,proto3,oneof"`
}

func (*VerifyRequirement_Compliance) isVerifyRequirement_Requirement() {}

type VerifyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUser    *TargetUser            `protobuf:"bytes,1,opt,name=target_user,proto3"`
	Requirements  []*VerifyRequirement   `protobuf:"bytes,2,rep,name=requirements,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserRequest) Reset() {
	*x = VerifyUserRequest{}
	mi := &file_auth_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserRequest) ProtoMessage() {}

func (x *VerifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyUserRequest) GetTargetUser() *TargetUser {
	if x != nil {
		return x.TargetUser
	}
	return nil
}

func (x *VerifyUserRequest) GetRequirements() []*VerifyRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type VerifyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserResponse) Reset() {
	*x = VerifyUserResponse{}
	mi := &file_auth_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserResponse) ProtoMessage() {}

func (x *VerifyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserResponse.ProtoReflect.Descriptor instead.
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyUserResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ExchangeExternalTokenForUserTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalToken string                 `protobuf:"bytes,1,opt,name=external_token,proto3"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeExternalTokenForUserTokenRequest) Reset() {
	*x = ExchangeExternalTokenForUserTokenRequest{}
	mi := &file_auth_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeExternalTokenForUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeExternalTokenForUserTokenRequest) ProtoMessage() {}

func (x *ExchangeExternalTokenForUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeExternalTokenForUserTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeExternalTokenForUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeExternalTokenForUserTokenRequest) GetExternalToken() string {
	if x != nil {
		return x.ExternalToken
	}
	return ""
}

func (x *ExchangeExternalTokenForUserTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type ExchangeExternalTokenForUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,proto3,oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeExternalTokenForUserTokenResponse) Reset() {
	*x = ExchangeExternalTokenForUserTokenResponse{}
	mi := &file_auth_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeExternalTokenForUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeExternalTokenForUserTokenResponse) ProtoMessage() {}

func (x *ExchangeExternalTokenForUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeExternalTokenForUserTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeExternalTokenForUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeExternalTokenForUserTokenResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

type ExchangeAPIKeyForUserTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAPIKeyForUserTokenRequest) Reset() {
	*x = ExchangeAPIKeyForUserTokenRequest{}
	mi := &file_auth_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAPIKeyForUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAPIKeyForUserTokenRequest) ProtoMessage() {}

func (x *ExchangeAPIKeyForUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAPIKeyForUserTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeAPIKeyForUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangeAPIKeyForUserTokenRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ExchangeAPIKeyForUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,proto3,oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAPIKeyForUserTokenResponse) Reset() {
	*x = ExchangeAPIKeyForUserTokenResponse{}
	mi := &file_auth_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAPIKeyForUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAPIKeyForUserTokenResponse) ProtoMessage() {}

func (x *ExchangeAPIKeyForUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAPIKeyForUserTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeAPIKeyForUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *ExchangeAPIKeyForUserTokenResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

var File_auth_exchange_proto protoreflect.FileDescriptor

const file_auth_exchange_proto_rawDesc = "" +
	"\n" +
	"\x13auth_exchange.proto\x12\bepic_urc\x1a\x12auth_session.proto\x1a\x10auth_token.proto\x1a\x0fauth_user.proto\"5\n" +
	"\x10VerifyCompliance\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\"f\n" +
	"\x11VerifyRequirement\x12<\n" +
	"\n" +
	"compliance\x18\x02 \x01(\v2\x1a.epic_urc.VerifyComplianceH\x00R\n" +
	"complianceB\r\n" +
	"\vrequirementJ\x04\b\x01\x10\x02\"\x8b\x01\n" +
	"\x11VerifyUserRequest\x125\n" +
	"\vtarget_user\x18\x01 \x01(\v2\x14.epic_urc.TargetUserR\n" +
	"targetUser\x12?\n" +
	"\frequirements\x18\x02 \x03(\v2\x1b.epic_urc.VerifyRequirementR\frequirements\"E\n" +
	"\x12VerifyUserResponse\x12/\n" +
	"\tuser_info\x18\x01 \x01(\v2\x12.epic_urc.UserInfoR\buserInfo\"p\n" +
	"(ExchangeExternalTokenForUserTokenRequest\x12%\n" +
	"\x0eexternal_token\x18\x01 \x01(\tR\rexternalToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\"s\n" +
	")ExchangeExternalTokenForUserTokenResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_token\"<\n" +
	"!ExchangeAPIKeyForUserTokenRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"l\n" +
	"\"ExchangeAPIKeyForUserTokenResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_tokenBDZBgithub.com/lorehub/lorehub/services/api/internal/loreauth/epic_urcb\x06proto3"

var (
	file_auth_exchange_proto_rawDescOnce sync.Once
	file_auth_exchange_proto_rawDescData []byte
)

func file_auth_exchange_proto_rawDescGZIP() []byte {
	file_auth_exchange_proto_rawDescOnce.Do(func() {
		file_auth_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(
			unsafe.Slice(unsafe.StringData(file_auth_exchange_proto_rawDesc), len(file_auth_exchange_proto_rawDesc)),
		)
	})
	return file_auth_exchange_proto_rawDescData
}

var file_auth_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_exchange_proto_goTypes = []any{
	(*VerifyCompliance)(nil),                          // 0: epic_urc.VerifyCompliance
	(*VerifyRequirement)(nil),                         // 1: epic_urc.VerifyRequirement
	(*VerifyUserRequest)(nil),                         // 2: epic_urc.VerifyUserRequest
	(*VerifyUserResponse)(nil),                        // 3: epic_urc.VerifyUserResponse
	(*ExchangeExternalTokenForUserTokenRequest)(nil),  // 4: epic_urc.ExchangeExternalTokenForUserTokenRequest
	(*ExchangeExternalTokenForUserTokenResponse)(nil), // 5: epic_urc.ExchangeExternalTokenForUserTokenResponse
	(*ExchangeAPIKeyForUserTokenRequest)(nil),         // 6: epic_urc.ExchangeAPIKeyForUserTokenRequest
	(*ExchangeAPIKeyForUserTokenResponse)(nil),        // 7: epic_urc.ExchangeAPIKeyForUserTokenResponse
	(*TargetUser)(nil),                                // 8: epic_urc.TargetUser
	(*UserInfo)(nil),                                  // 9: epic_urc.UserInfo
	(*UserToken)(nil),                                 // 10: epic_urc.UserToken
}
var file_auth_exchange_proto_depIdxs = []int32{
	0,  // 0: epic_urc.VerifyRequirement.compliance:type_name -> epic_urc.VerifyCompliance
	8,  // 1: epic_urc.VerifyUserRequest.target_user:type_name -> epic_urc.TargetUser
	1,  // 2: epic_urc.VerifyUserRequest.requirements:type_name -> epic_urc.VerifyRequirement
	9,  // 3: epic_urc.VerifyUserResponse.user_info:type_name -> epic_urc.UserInfo
	10, // 4: epic_urc.ExchangeExternalTokenForUserTokenResponse.user_token:type_name -> epic_urc.UserToken
	10, // 5: epic_urc.ExchangeAPIKeyForUserTokenResponse.user_token:type_name -> epic_urc.UserToken
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_auth_exchange_proto_init() }
func file_auth_exchange_proto_init() {
	if File_auth_exchange_proto != nil {
		return
	}
	file_auth_session_proto_init()
	file_auth_token_proto_init()
	file_auth_user_proto_init()
	file_auth_exchange_proto_msgTypes[1].OneofWrappers = []any{
		(*VerifyRequirement_Compliance)(nil),
	}
	file_auth_exchange_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_exchange_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(
				unsafe.StringData(file_auth_exchange_proto_rawDesc),
				len(file_auth_exchange_proto_rawDesc),
			),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_exchange_proto_goTypes,
		DependencyIndexes: file_auth_exchange_proto_depIdxs,
		MessageInfos:      file_auth_exchange_proto_msgTypes,
	}.Build()
	File_auth_exchange_proto = out.File
	file_auth_exchange_proto_goTypes = nil
	file_auth_exchange_proto_depIdxs = nil
}
