// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: auth_api.proto

package epic_urc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_api_proto protoreflect.FileDescriptor

const file_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x0eauth_api.proto\x12\bepic_urc\x1a\x12auth_session.proto\x1a\x13auth_exchange.pr" +
	"oto\x1a\x15auth_permission.proto\x1a\x0fauth_user.proto2\xb0\n" +
	"\n" +
	"\n" +
	"UrcAuthApi\x12L\n" +
	"\vHealthCheck\x12\x1c.epic_urc.HealthCheckRequest\x1a\x1d.epic_urc.HealthCheckResponse\"\x00\x12[\n" +
	"\x10StartAuthSession\x12!.epic_urc.StartAuthSessionRequest\x1a\".epic_urc.StartAuthSessionResponse\"\x00\x12U\n" +
	"\x0eGetAuthSession\x12\x1f.epic_urc.GetAuthSessionRequest\x1a .epic_urc.GetAuthSessionResponse\"\x00\x12a\n" +
	"\x12RefreshAuthSession\x12#.epic_urc.RefreshAuthSessionRequest\x1a$.epic_urc.Refre" +
	"shAuthSessionResponse\"\x00\x12I\n" +
	"\n" +
	"VerifyUser\x12\x1b.epic_urc.VerifyUserRequest\x1a\x1c.epic_urc.VerifyUserResponse\"\x00\x12\x8e\x01\n" +
	"!ExchangeExternalTokenForUserToken\x122.epic_urc.ExchangeExternalTokenForUserToken" +
	"Request\x1a3.epic_urc.ExchangeExternalTokenForUserTokenResponse\"\x00\x12y\n" +
	"\x1aExchangeAPIKeyForUserToken\x12+.epic_urc.ExchangeAPIKeyForUserTokenRequest\x1a" +
	",.epic_urc.ExchangeAPIKeyForUserTokenResponse\"\x00\x12\x9d\x01\n" +
	"&ExchangeUserTokenForMultiresourceToken\x127.epic_urc.ExchangeUserTokenForMultires" +
	"ourceTokenRequest\x1a8.epic_urc.ExchangeUserTokenForMultiresourceTokenResponse\"" +
	"\x00\x12d\n" +
	"\x13CheckUserPermission\x12$.epic_urc.CheckUserPermissionRequest\x1a%.epic_urc.Che" +
	"ckUserPermissionResponse\"\x00\x12j\n" +
	"\x15LookupUserPermissions\x12&.epic_urc.LookupUserPermissionsRequest\x1a'.epic_urc" +
	".LookupUserPermissionsResponse\"\x00\x12L\n" +
	"\vGetUserInfo\x12\x1c.epic_urc.GetUserInfoRequest\x1a\x1d.epic_urc.GetUserInfoResponse\"\x00\x12F\n" +
	"\tGetUserId\x12\x1a.epic_urc.GetUserIdRequest\x1a\x1b.epic_urc.GetUserIdResponse\"\x00\x12^\n" +
	"\x11GetProviderUserId\x12\".epic_urc.GetProviderUserIdRequest\x1a#.epic_urc.GetPro" +
	"viderUserIdResponse\"\x00BDZBgithub.com/lorehub/lorehub/services/api/internal/lore" +
	"auth/epic_urcb\x06proto3"

var file_auth_api_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),                             // 0: epic_urc.HealthCheckRequest
	(*StartAuthSessionRequest)(nil),                        // 1: epic_urc.StartAuthSessionRequest
	(*GetAuthSessionRequest)(nil),                          // 2: epic_urc.GetAuthSessionRequest
	(*RefreshAuthSessionRequest)(nil),                      // 3: epic_urc.RefreshAuthSessionRequest
	(*VerifyUserRequest)(nil),                              // 4: epic_urc.VerifyUserRequest
	(*ExchangeExternalTokenForUserTokenRequest)(nil),       // 5: epic_urc.ExchangeExternalTokenForUserTokenRequest
	(*ExchangeAPIKeyForUserTokenRequest)(nil),              // 6: epic_urc.ExchangeAPIKeyForUserTokenRequest
	(*ExchangeUserTokenForMultiresourceTokenRequest)(nil),  // 7: epic_urc.ExchangeUserTokenForMultiresourceTokenRequest
	(*CheckUserPermissionRequest)(nil),                     // 8: epic_urc.CheckUserPermissionRequest
	(*LookupUserPermissionsRequest)(nil),                   // 9: epic_urc.LookupUserPermissionsRequest
	(*GetUserInfoRequest)(nil),                             // 10: epic_urc.GetUserInfoRequest
	(*GetUserIdRequest)(nil),                               // 11: epic_urc.GetUserIdRequest
	(*GetProviderUserIdRequest)(nil),                       // 12: epic_urc.GetProviderUserIdRequest
	(*HealthCheckResponse)(nil),                            // 13: epic_urc.HealthCheckResponse
	(*StartAuthSessionResponse)(nil),                       // 14: epic_urc.StartAuthSessionResponse
	(*GetAuthSessionResponse)(nil),                         // 15: epic_urc.GetAuthSessionResponse
	(*RefreshAuthSessionResponse)(nil),                     // 16: epic_urc.RefreshAuthSessionResponse
	(*VerifyUserResponse)(nil),                             // 17: epic_urc.VerifyUserResponse
	(*ExchangeExternalTokenForUserTokenResponse)(nil),      // 18: epic_urc.ExchangeExternalTokenForUserTokenResponse
	(*ExchangeAPIKeyForUserTokenResponse)(nil),             // 19: epic_urc.ExchangeAPIKeyForUserTokenResponse
	(*ExchangeUserTokenForMultiresourceTokenResponse)(nil), // 20: epic_urc.ExchangeUserTokenForMultiresourceTokenResponse
	(*CheckUserPermissionResponse)(nil),                    // 21: epic_urc.CheckUserPermissionResponse
	(*LookupUserPermissionsResponse)(nil),                  // 22: epic_urc.LookupUserPermissionsResponse
	(*GetUserInfoResponse)(nil),                            // 23: epic_urc.GetUserInfoResponse
	(*GetUserIdResponse)(nil),                              // 24: epic_urc.GetUserIdResponse
	(*GetProviderUserIdResponse)(nil),                      // 25: epic_urc.GetProviderUserIdResponse
}
var file_auth_api_proto_depIdxs = []int32{
	0, // 0: epic_urc.UrcAuthApi.HealthCheck:input_type -> epic_urc.HealthCheckRequest
	1, // 1: epic_urc.UrcAuthApi.StartAuthSession:input_type -> epic_urc.StartAuthSessionRequest
	2, // 2: epic_urc.UrcAuthApi.GetAuthSession:input_type -> epic_urc.GetAuthSessionRequest
	3, // 3: epic_urc.UrcAuthApi.RefreshAuthSession:input_type -> epic_urc.RefreshAuthSessionRequest
	4, // 4: epic_urc.UrcAuthApi.VerifyUser:input_type -> epic_urc.VerifyUserRequest
	5, // 5: epic_urc.UrcAuthApi.ExchangeExternalTokenForUserToken:input_type ->
	// epic_urc.ExchangeExternalTokenForUserTokenRequest
	6, // 6: epic_urc.UrcAuthApi.ExchangeAPIKeyForUserToken:input_type -> epic_urc.ExchangeAPIKeyForUserTokenRequest
	7, // 7: epic_urc.UrcAuthApi.ExchangeUserTokenForMultiresourceToken:input_type ->
	// epic_urc.ExchangeUserTokenForMultiresourceTokenRequest
	8,  // 8: epic_urc.UrcAuthApi.CheckUserPermission:input_type -> epic_urc.CheckUserPermissionRequest
	9,  // 9: epic_urc.UrcAuthApi.LookupUserPermissions:input_type -> epic_urc.LookupUserPermissionsRequest
	10, // 10: epic_urc.UrcAuthApi.GetUserInfo:input_type -> epic_urc.GetUserInfoRequest
	11, // 11: epic_urc.UrcAuthApi.GetUserId:input_type -> epic_urc.GetUserIdRequest
	12, // 12: epic_urc.UrcAuthApi.GetProviderUserId:input_type -> epic_urc.GetProviderUserIdRequest
	13, // 13: epic_urc.UrcAuthApi.HealthCheck:output_type -> epic_urc.HealthCheckResponse
	14, // 14: epic_urc.UrcAuthApi.StartAuthSession:output_type -> epic_urc.StartAuthSessionResponse
	15, // 15: epic_urc.UrcAuthApi.GetAuthSession:output_type -> epic_urc.GetAuthSessionResponse
	16, // 16: epic_urc.UrcAuthApi.RefreshAuthSession:output_type -> epic_urc.RefreshAuthSessionResponse
	17, // 17: epic_urc.UrcAuthApi.VerifyUser:output_type -> epic_urc.VerifyUserResponse
	18, // 18: epic_urc.UrcAuthApi.ExchangeExternalTokenForUserToken:output_type ->
	// epic_urc.ExchangeExternalTokenForUserTokenResponse
	19, // 19: epic_urc.UrcAuthApi.ExchangeAPIKeyForUserToken:output_type -> epic_urc.ExchangeAPIKeyForUserTokenResponse
	20, // 20: epic_urc.UrcAuthApi.ExchangeUserTokenForMultiresourceToken:output_type ->
	// epic_urc.ExchangeUserTokenForMultiresourceTokenResponse
	21, // 21: epic_urc.UrcAuthApi.CheckUserPermission:output_type -> epic_urc.CheckUserPermissionResponse
	22, // 22: epic_urc.UrcAuthApi.LookupUserPermissions:output_type -> epic_urc.LookupUserPermissionsResponse
	23, // 23: epic_urc.UrcAuthApi.GetUserInfo:output_type -> epic_urc.GetUserInfoResponse
	24, // 24: epic_urc.UrcAuthApi.GetUserId:output_type -> epic_urc.GetUserIdResponse
	25, // 25: epic_urc.UrcAuthApi.GetProviderUserId:output_type -> epic_urc.GetProviderUserIdResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_api_proto_init() }
func file_auth_api_proto_init() {
	if File_auth_api_proto != nil {
		return
	}
	file_auth_session_proto_init()
	file_auth_exchange_proto_init()
	file_auth_permission_proto_init()
	file_auth_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_api_proto_rawDesc), len(file_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_api_proto_goTypes,
		DependencyIndexes: file_auth_api_proto_depIdxs,
	}.Build()
	File_auth_api_proto = out.File
	file_auth_api_proto_goTypes = nil
	file_auth_api_proto_depIdxs = nil
}
