// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: auth_token.proto

package epic_urc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     string                 `protobuf:"bytes,1,opt,name=user_token,proto3"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,proto3"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,proto3"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserToken) Reset() {
	*x = UserToken{}
	mi := &file_auth_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToken) ProtoMessage() {}

func (x *UserToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToken.ProtoReflect.Descriptor instead.
func (*UserToken) Descriptor() ([]byte, []int) {
	return file_auth_token_proto_rawDescGZIP(), []int{0}
}

func (x *UserToken) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *UserToken) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *UserToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserToken) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

var File_auth_token_proto protoreflect.FileDescriptor

const file_auth_token_proto_rawDesc = "" +
	"\n" +
	"\x10auth_token.proto\x12\bepic_urc\"\x7f\n" +
	"\tUserToken\x12\x1d\n" +
	"\n" +
	"user_token\x18\x01 \x01(\tR\tuserToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserNameBDZBgithub.com/lorehub/lorehub/services/api/" +
	"internal/loreauth/epic_urcb\x06proto3"

var (
	file_auth_token_proto_rawDescOnce sync.Once
	file_auth_token_proto_rawDescData []byte
)

func file_auth_token_proto_rawDescGZIP() []byte {
	file_auth_token_proto_rawDescOnce.Do(func() {
		file_auth_token_proto_rawDescData = protoimpl.X.CompressGZIP(
			unsafe.Slice(unsafe.StringData(file_auth_token_proto_rawDesc), len(file_auth_token_proto_rawDesc)),
		)
	})
	return file_auth_token_proto_rawDescData
}

var file_auth_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_token_proto_goTypes = []any{
	(*UserToken)(nil), // 0: epic_urc.UserToken
}
var file_auth_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_token_proto_init() }
func file_auth_token_proto_init() {
	if File_auth_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_token_proto_rawDesc), len(file_auth_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_token_proto_goTypes,
		DependencyIndexes: file_auth_token_proto_depIdxs,
		MessageInfos:      file_auth_token_proto_msgTypes,
	}.Build()
	File_auth_token_proto = out.File
	file_auth_token_proto_goTypes = nil
	file_auth_token_proto_depIdxs = nil
}
