// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: auth_user.proto

package epic_urc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,proto3"`
	UserId        []string               `protobuf:"bytes,2,rep,name=user_id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_auth_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetUserInfoRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,proto3"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_auth_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      []*UserInfo            `protobuf:"bytes,1,rep,name=user_info,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_auth_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoResponse) GetUserInfo() []*UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetUserIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceId      string                 `protobuf:"bytes,1,opt,name=resource_id,proto3"`
	UserDisplayName string                 `protobuf:"bytes,2,opt,name=user_display_name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserIdRequest) Reset() {
	*x = GetUserIdRequest{}
	mi := &file_auth_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdRequest) ProtoMessage() {}

func (x *GetUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserIdRequest) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserIdRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetUserIdRequest) GetUserDisplayName() string {
	if x != nil {
		return x.UserDisplayName
	}
	return ""
}

type GetUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIdResponse) Reset() {
	*x = GetUserIdResponse{}
	mi := &file_auth_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdResponse) ProtoMessage() {}

func (x *GetUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserIdResponse) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserIdResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetProviderUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderUserIdRequest) Reset() {
	*x = GetProviderUserIdRequest{}
	mi := &file_auth_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderUserIdRequest) ProtoMessage() {}

func (x *GetProviderUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetProviderUserIdRequest) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetProviderUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProviderUserIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,proto3"`
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProviderUserIdResponse) Reset() {
	*x = GetProviderUserIdResponse{}
	mi := &file_auth_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderUserIdResponse) ProtoMessage() {}

func (x *GetProviderUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetProviderUserIdResponse) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetProviderUserIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProviderUserIdResponse) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

var File_auth_user_proto protoreflect.FileDescriptor

const file_auth_user_proto_rawDesc = "" +
	"\n" +
	"\x0fauth_user.proto\x12\bepic_urc\"N\n" +
	"\x12GetUserInfoRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x17\n" +
	"\auser_id\x18\x02 \x03(\tR\x06userId\"F\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"F\n" +
	"\x13GetUserInfoResponse\x12/\n" +
	"\tuser_info\x18\x01 \x03(\v2\x12.epic_urc.UserInfoR\buserInfo\"_\n" +
	"\x10GetUserIdRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12*\n" +
	"\x11user_display_name\x18\x02 \x01(\tR\x0fuserDisplayName\"D\n" +
	"\x11GetUserIdResponse\x12/\n" +
	"\tuser_info\x18\x01 \x01(\v2\x12.epic_urc.UserInfoR\buserInfo\"3\n" +
	"\x18GetProviderUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x19GetProviderUserIdResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserIdBDZBgithub.com/lorehub/lore" +
	"hub/services/api/internal/loreauth/epic_urcb\x06proto3"

var (
	file_auth_user_proto_rawDescOnce sync.Once
	file_auth_user_proto_rawDescData []byte
)

func file_auth_user_proto_rawDescGZIP() []byte {
	file_auth_user_proto_rawDescOnce.Do(func() {
		file_auth_user_proto_rawDescData = protoimpl.X.CompressGZIP(
			unsafe.Slice(unsafe.StringData(file_auth_user_proto_rawDesc), len(file_auth_user_proto_rawDesc)),
		)
	})
	return file_auth_user_proto_rawDescData
}

var file_auth_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_user_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),        // 0: epic_urc.GetUserInfoRequest
	(*UserInfo)(nil),                  // 1: epic_urc.UserInfo
	(*GetUserInfoResponse)(nil),       // 2: epic_urc.GetUserInfoResponse
	(*GetUserIdRequest)(nil),          // 3: epic_urc.GetUserIdRequest
	(*GetUserIdResponse)(nil),         // 4: epic_urc.GetUserIdResponse
	(*GetProviderUserIdRequest)(nil),  // 5: epic_urc.GetProviderUserIdRequest
	(*GetProviderUserIdResponse)(nil), // 6: epic_urc.GetProviderUserIdResponse
}
var file_auth_user_proto_depIdxs = []int32{
	1, // 0: epic_urc.GetUserInfoResponse.user_info:type_name -> epic_urc.UserInfo
	1, // 1: epic_urc.GetUserIdResponse.user_info:type_name -> epic_urc.UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_user_proto_init() }
func file_auth_user_proto_init() {
	if File_auth_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_user_proto_rawDesc), len(file_auth_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_user_proto_goTypes,
		DependencyIndexes: file_auth_user_proto_depIdxs,
		MessageInfos:      file_auth_user_proto_msgTypes,
	}.Build()
	File_auth_user_proto = out.File
	file_auth_user_proto_goTypes = nil
	file_auth_user_proto_depIdxs = nil
}
